# Generated by Django 3.0.5 on 2020-08-02 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('Storage_details', models.CharField(max_length=150)),
                ('Screen_size', models.CharField(max_length=150)),
                ('Camera_details', models.CharField(max_length=150)),
                ('Battery_details', models.CharField(max_length=150)),
                ('Processor', models.CharField(max_length=150)),
                ('Warranty', models.CharField(max_length=150)),
                ('Price', models.IntegerField()),
            ],
        ),
    ]
